export const DEFAULT_STATE = '@@redux/INIT';
export const MODE_CHANGED = 'MODE_CHANGED';
export const SWITCH_MESSAGE = 'SWITCH_MESSAGE';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const NEW_MESSAGE = 'NEW_MESSAGE';

export const TOGGLE_SEGMENT_ACCORDION = 'TOGGLE_SEGMENT_ACCORDION';
export const TOGGLE_FIELD_ACCORDION = 'TOGGLE_FIELD_ACCORDION';
export const TOGGLE_COMPONENT_ACCORDION = 'TOGGLE_COMPONENT_ACCORDION';

export const DEFAULT_SEGMENT_ACCORDIONS = 'DEFAULT_SEGMENT_ACCORDIONS';
export const DEFAULT_FIELD_ACCORDIONS = 'DEFAULT_FIELD_ACCORDIONS';
export const DEFAULT_COMPONENT_ACCORDIONS = 'DEFAULT_COMPONENT_ACCORDIONS';
export const DEFAULT_MESSAGE_ACCORDIONS = 'DEFAULT_MESSAGE_ACCORDIONS';



