export const DEFAULT_STATE = '@@redux/INIT';
export const MODE_CHANGED = 'MODE_CHANGED';
export const SWITCH_MESSAGE = 'SWITCH_MESSAGE';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const NEW_MESSAGE = 'NEW_MESSAGE';

export const TOGGLE_SEGMENT_ACCORDION = 'TOGGLE_SEGMENT_ACCORDION';
export const TOGGLE_FIELD_ACCORDION = 'TOGGLE_FIELD_ACCORDION';
export const TOGGLE_COMPONENT_ACCORDION = 'TOGGLE_COMPONENT_ACCORDION';
export const TOGGLE_REPEAT_FIELD_ACCORDION = 'TOGGLE_REPEAT_FIELD_ACCORDION';

export const DEFAULT_SEGMENT_ACCORDIONS = 'DEFAULT_SEGMENT_ACCORDIONS';
export const DEFAULT_FIELD_ACCORDIONS = 'DEFAULT_FIELD_ACCORDIONS';
export const DEFAULT_COMPONENT_ACCORDIONS = 'DEFAULT_COMPONENT_ACCORDIONS';
export const DEFAULT_MESSAGE_ACCORDIONS = 'DEFAULT_MESSAGE_ACCORDIONS';
export const DEFAULT_REPEAT_FIELD_ACCORDIONS = 'DEFAULT_REPEAT_FIELD_ACCORDIONS';
export const DEFAULT_REPEAT_COMPONENT_ACCORDIONS = 'DEFAULT_REPEAT_COMPONENT_ACCORDIONS';
export const TOGGLE_REPEAT_COMPONENT_ACCORDION = 'TOGGLE_REPEAT_COMPONENT_ACCORDION';

export const ADD_SEARCH_CONDITION = 'ADD_SEARCH_CONDITION';
export const ADD_SEARCH_GROUP_CONDITION = 'ADD_SEARCH_GROUP_CONDITION';
export const UPDATE_GROUP_OPERAND = 'UPDATE_GROUP_OPERAND';
export const UPDATE_SEARCH_OPERAND = 'UPDATE_SEARCH_OPERAND';
export const DELETE_SINGLE_CONDITION = 'DELETE_SINGLE_CONDITION';
export const ADD_GROUP_SIZE = 'ADD_GROUP_SIZE';
export const ADD_CONDITION_SIZE = 'ADD_CONDITION_SIZE';

export const NEW_SEARCH_RESULT = 'NEW_SEARCH_RESULT';
export const NEW_SEARCH_MESSAGE = 'NEW_SEARCH_MESSAGE';
export const REMOVE_SEARCH_FILTER = 'REMOVE_SEARCH_FILTER';
export const SAVE_SEARCH = 'SAVE_SEARCH';





